// Glossary data - single source of truth for all formats
// Used by: /glossary page, /api/glossary, /glossary.json, JSON-LD schema

export interface GlossaryTerm {
  id: string;
  term: string;
  pronunciation?: string;
  arabicScript?: string;
  tifinagh?: string;
  category: string;
  definition: string;
  context?: string;
  related?: string[];
  seeAlso?: string[]; // links to other glossary terms by id
  // Cross-links to content
  relatedJourneys?: { slug: string; title: string }[];
  relatedStories?: { slug: string; title: string }[];
  relatedPlaces?: { slug: string; title: string }[];
}

export interface GlossaryCategory {
  id: string;
  title: string;
  description?: string;
  terms: GlossaryTerm[];
}

export const glossaryData: GlossaryCategory[] = [
  {
    id: "cities-regions",
    title: "Cities & Regions",
    description: "Morocco's major destinations, from imperial cities to mountain ranges and desert valleys.",
    terms: [
      {
        id: "marrakech",
        term: "Marrakech",
        pronunciation: "ma-ra-KESH",
        arabicScript: "مراكش",
        tifinagh: "ⵎⵕⵕⴰⴽⵛ",
        category: "cities-regions",
        definition: "Morocco's fourth-largest city and most visited destination, founded in 1070 by the Almoravid dynasty. One of the four imperial cities, known for its red earth walls, historic medina, and position as the gateway to the High Atlas and Sahara.",
        context: "The city's name may derive from Amazigh 'mur n akush' (Land of God). The distinctive red-ochre buildings gave Morocco its nickname 'The Red City' and influenced the country's name in several languages.",
        related: ["imperial city", "medina", "Red City"],
        seeAlso: ["jemaa-el-fna", "koutoubia-mosque", "medina"],
        relatedJourneys: [
          { slug: "7-Day-Atlas-to-Desert", title: "Atlas to Desert Journey" },
          { slug: "3-Day-Marrakech-Essaouira", title: "Marrakech & Essaouira" },
        ],
        relatedStories: [
          { slug: "the-language-of-walls", title: "The Language of Walls" },
          { slug: "the-garden-within", title: "The Garden Within" },
        ],
        relatedPlaces: [
          { slug: "marrakech", title: "Marrakech" },
        ],
      },
      {
        id: "fes",
        term: "Fes",
        pronunciation: "fez",
        arabicScript: "فاس",
        tifinagh: "ⴼⴰⵙ",
        category: "cities-regions",
        definition: "Morocco's spiritual and intellectual capital, founded in 789 CE by Idris I. Home to the world's oldest continuously operating university (Al-Qarawiyyin, founded 859 CE) and the best-preserved medieval medina in the Arab world.",
        context: "Fes was Morocco's capital for most of its history until 1912. The city remains the center of traditional crafts, religious learning, and Moroccan haute cuisine. The red felt hat 'fez' takes its name from the city.",
        related: ["imperial city", "Al-Qarawiyyin", "medina"],
        seeAlso: ["fes-el-bali", "chouara-tannery", "fondouk"],
        relatedJourneys: [
          { slug: "8-Day-Imperial-Cities", title: "Imperial Cities Journey" },
          { slug: "10-Day-Northern-Morocco", title: "Northern Morocco" },
        ],
        relatedStories: [
          { slug: "the-geometry-of-faith", title: "The Geometry of Faith" },
          { slug: "the-tanners-art", title: "The Tanner's Art" },
        ],
        relatedPlaces: [
          { slug: "fes", title: "Fes" },
        ],
      },
      {
        id: "tangier",
        term: "Tangier",
        pronunciation: "tan-JEER",
        arabicScript: "طنجة",
        tifinagh: "ⵟⴰⵏⵊⴰ",
        category: "cities-regions",
        definition: "A port city on the Strait of Gibraltar where the Atlantic meets the Mediterranean, just 14 kilometers from Spain. Its strategic position made it a contested prize throughout history—ruled by Phoenicians, Romans, Portuguese, British, and as an international zone (1923-1956).",
        context: "Tangier's cosmopolitan history attracted writers and artists including Paul Bowles, William S. Burroughs, and Henri Matisse. The medina's Petit Socco was once the hub of espionage and intrigue.",
        related: ["Strait of Gibraltar", "international zone", "Beat Generation"],
        seeAlso: ["medina"],
      },
      {
        id: "rabat",
        term: "Rabat",
        pronunciation: "ra-BAT",
        arabicScript: "الرباط",
        tifinagh: "ⵕⵕⴱⴰⵟ",
        category: "cities-regions",
        definition: "Morocco's capital since 1912 and one of the four imperial cities. Founded as a fortified monastery (ribat) in the 12th century by the Almohads, it retains a more European character than other Moroccan cities.",
        context: "The French made Rabat the capital during the Protectorate, and it remains the seat of government and home to the royal palace. The Kasbah of the Udayas and Hassan Tower are its main historic sites.",
        related: ["imperial city", "capital", "Almohad dynasty"],
        seeAlso: ["hassan-tower", "kasbah"],
      },
      {
        id: "casablanca",
        term: "Casablanca",
        pronunciation: "ka-sa-BLAN-ka",
        arabicScript: "الدار البيضاء",
        tifinagh: "ⴰⵏⴼⴰ",
        category: "cities-regions",
        definition: "Morocco's largest city and economic capital, home to nearly 4 million people. A 20th-century creation—the French transformed a small port into a showcase of Art Deco architecture and Morocco's commercial hub.",
        context: "The Arabic name 'Dar el-Beida' (White House) and Spanish 'Casablanca' both refer to a whitewashed landmark. The Hassan II Mosque, completed in 1993, has the world's tallest minaret at 210 meters.",
        related: ["Art Deco", "Hassan II Mosque", "economic capital"],
      },
      {
        id: "meknes",
        term: "Meknes",
        pronunciation: "mek-NES",
        arabicScript: "مكناس",
        tifinagh: "ⵎⴽⵏⴰⵙ",
        category: "cities-regions",
        definition: "The smallest of Morocco's four imperial cities, transformed by Sultan Moulay Ismail (1672-1727) into a rival to Versailles. Known for its monumental gates, vast granaries, and proximity to Roman Volubilis.",
        context: "Moulay Ismail stripped the Palais El Badi in Marrakech to build his new capital. The city's 40 kilometers of walls once enclosed palaces, gardens, and stables for 12,000 horses.",
        related: ["imperial city", "Moulay Ismail", "Bab Mansour"],
        seeAlso: ["volubilis"],
      },
      {
        id: "ouarzazate",
        term: "Ouarzazate",
        pronunciation: "war-za-ZAT",
        arabicScript: "ورزازات",
        tifinagh: "ⵡⴰⵔⵣⴰⵣⴰⵜ",
        category: "cities-regions",
        definition: "A desert crossroads city at the meeting point of the Draa and Dades valleys, gateway to the Sahara. Known as the 'Hollywood of Morocco' for its film studios where Lawrence of Arabia, Gladiator, and Game of Thrones were filmed.",
        context: "The name comes from Amazigh 'war zazat' (without noise/confusion). The nearby Taourirt Kasbah and Atlas Film Studios are major attractions.",
        related: ["film studios", "Taourirt Kasbah", "desert gateway"],
        seeAlso: ["ait-benhaddou", "draa-valley"],
      },
      {
        id: "draa-valley",
        term: "Draa Valley",
        pronunciation: "dra",
        arabicScript: "وادي درعة",
        tifinagh: "ⴰⵙⵉⴼ ⵏ ⴷⵔⴰ",
        category: "cities-regions",
        definition: "Morocco's longest river valley, stretching 1,100 kilometers from the High Atlas to the Atlantic (though it rarely reaches the sea). The middle section between Agdz and Zagora is a ribbon of palm oases, kasbahs, and ksour.",
        context: "The valley was a crucial trans-Saharan trade route, with caravans carrying gold, salt, and slaves. Today it's known for dates—over 4 million palm trees produce some of Morocco's finest varieties.",
        related: ["palm oasis", "trans-Saharan trade", "Zagora", "Agdz"],
        seeAlso: ["kasbah", "ksar"],
        relatedJourneys: [
          { slug: "10-Day-Southern-Oases", title: "Southern Oases Route" },
          { slug: "7-Day-Atlas-to-Desert", title: "Atlas to Desert" },
        ],
        relatedStories: [
          { slug: "the-fortress-of-grain", title: "The Fortress of Grain" },
          { slug: "the-last-caravanserai", title: "The Last Caravanserai" },
        ],
        relatedPlaces: [
          { slug: "zagora", title: "Zagora" },
          { slug: "tamegroute", title: "Tamegroute" },
        ],
      },
      {
        id: "high-atlas",
        term: "High Atlas",
        pronunciation: "AT-las",
        arabicScript: "الأطلس الكبير",
        tifinagh: "ⴰⵟⵍⴰⵙ ⴰⵎⵇⵇⵔⴰⵏ",
        category: "cities-regions",
        definition: "North Africa's highest mountain range, stretching 1,000 kilometers across Morocco with peaks exceeding 4,000 meters. Jebel Toubkal (4,167m) is the highest point in North Africa. The range separates the Atlantic plains from the Sahara.",
        context: "The High Atlas is home to Amazigh communities who have maintained traditional lifestyles in remote villages. Imlil is the main trekking base; the Tizi n'Tichka pass (2,260m) is the main route to the south.",
        related: ["Jebel Toubkal", "Imlil", "Tizi n'Tichka", "Amazigh"],
        seeAlso: ["amazigh"],
        relatedJourneys: [
          { slug: "7-Day-Atlas-Valleys", title: "Atlas Valleys Journey" },
          { slug: "5-Day-Toubkal-Trek", title: "Toubkal Trek" },
        ],
        relatedStories: [
          { slug: "the-silence-of-stone", title: "The Silence of Stone" },
          { slug: "the-language-of-wool", title: "The Language of Wool" },
        ],
        relatedPlaces: [
          { slug: "imlil", title: "Imlil" },
          { slug: "ouirgane", title: "Ouirgane" },
        ],
      },
      {
        id: "middle-atlas",
        term: "Middle Atlas",
        pronunciation: "AT-las",
        arabicScript: "الأطلس المتوسط",
        category: "cities-regions",
        definition: "A mountain range between Fes and the High Atlas, characterized by cedar forests, crater lakes, and Amazigh villages. Lower and greener than the High Atlas, with peaks around 3,300 meters.",
        context: "Ifrane, founded by the French as a hill station, is known as 'Morocco's Switzerland.' The cedar forests shelter the endangered Barbary macaque, North Africa's only wild primate.",
        related: ["Ifrane", "cedar forest", "Barbary macaque", "Azrou"],
      },
      {
        id: "anti-atlas",
        term: "Anti-Atlas",
        pronunciation: "AN-tee AT-las",
        arabicScript: "الأطلس الصغير",
        tifinagh: "ⴰⵟⵍⴰⵙ ⴰⵎⵥⵢⴰⵏ",
        category: "cities-regions",
        definition: "An ancient mountain range south of the High Atlas, with dramatic geological formations dating back 2 billion years. Lower and drier than other Atlas ranges, with pink granite, volcanic plugs, and prehistoric rock engravings.",
        context: "The Ameln Valley near Tafraoute showcases traditional Amazigh architecture against surreal boulder-strewn landscapes. Belgian artist Jean Vérame painted several boulders blue in 1984.",
        related: ["Tafraoute", "Ameln Valley", "prehistoric rock art"],
      },
      {
        id: "rif-mountains",
        term: "Rif Mountains",
        pronunciation: "rif",
        arabicScript: "جبال الريف",
        tifinagh: "ⴰⵔⵔⵉⴼ",
        category: "cities-regions",
        definition: "A crescent-shaped mountain range along Morocco's Mediterranean coast, historically isolated and fiercely independent. The Rif's terrain sheltered resistance to colonial powers and today produces most of the world's cannabis resin.",
        context: "The Rif was the last region to submit to French and Spanish colonial control and has retained a distinct Amazigh identity. Chefchaouen and Akchour waterfalls are the main tourist draws.",
        related: ["Chefchaouen", "Mediterranean coast", "Amazigh"],
        seeAlso: ["chefchaouen"],
      },
      {
        id: "sahara",
        term: "Sahara",
        pronunciation: "sa-HA-ra",
        arabicScript: "الصحراء",
        category: "cities-regions",
        definition: "The world's largest hot desert, covering 9 million square kilometers across North Africa. Morocco's portion includes sand dune fields (ergs), stone plateaus (hammadas), and gravel plains (regs).",
        context: "Only about 25% of the Sahara is sand dunes—the rest is rock and gravel. Morocco's most accessible Saharan dunes are at Erg Chebbi (Merzouga) and Erg Chigaga (M'Hamid).",
        related: ["Merzouga", "M'Hamid", "desert"],
        seeAlso: ["erg", "hammada", "reg", "erg-chebbi"],
        relatedJourneys: [
          { slug: "3-Day-Desert-Experience", title: "Sahara Desert Experience" },
          { slug: "8-Day-Desert-Circle", title: "The Desert Circle" },
        ],
        relatedStories: [
          { slug: "the-blue-men", title: "The Blue Men" },
          { slug: "stars-over-sand", title: "Stars Over Sand" },
        ],
        relatedPlaces: [
          { slug: "merzouga", title: "Merzouga" },
          { slug: "mhamid", title: "M'Hamid" },
        ],
      },
      {
        id: "souss-valley",
        term: "Souss Valley",
        pronunciation: "soos",
        arabicScript: "وادي سوس",
        tifinagh: "ⵙⵓⵙ",
        category: "cities-regions",
        definition: "A fertile agricultural plain between the High Atlas and Anti-Atlas, centered on Agadir. Morocco's largest producer of citrus and early vegetables, with extensive argan tree forests unique to this region.",
        context: "The valley has been an Amazigh heartland for millennia. Taroudant, the 'Grandmother of Marrakech,' preserves ramparts and souks predating the Red City.",
        related: ["Agadir", "Taroudant", "argan", "Amazigh"],
        seeAlso: ["argan"],
      },
      {
        id: "tafilalt",
        term: "Tafilalt",
        pronunciation: "ta-fee-LALT",
        arabicScript: "تافيلالت",
        tifinagh: "ⵜⴰⴼⵉⵍⴰⵍⵜ",
        category: "cities-regions",
        definition: "A historic oasis region in southeastern Morocco, once the terminus of trans-Saharan trade routes. The area around Erfoud and Rissani was the cradle of the Alaouite dynasty, Morocco's ruling family since 1631.",
        context: "Tafilalt dates are prized throughout Morocco. The region is also known for fossil beds containing 400-million-year-old trilobites and ammonites.",
        related: ["Erfoud", "Rissani", "Alaouite dynasty", "dates", "fossils"],
        seeAlso: ["erg-chebbi"],
      },
      {
        id: "atlantic-coast",
        term: "Atlantic Coast",
        pronunciation: "at-LAN-tik",
        category: "cities-regions",
        definition: "Morocco's 2,000-kilometer western coastline, from Tangier to the Western Sahara. Known for fishing ports, surf towns, and coastal cities including Casablanca, Rabat, and Essaouira.",
        context: "The coast benefits from the cool Canary Current, making it pleasant even in summer. Essaouira and Taghazout are popular surf destinations; Dakhla in the south is a world-class kitesurfing spot.",
        related: ["Essaouira", "Taghazout", "Dakhla", "surfing"],
        seeAlso: ["essaouira-medina"],
      },
    ],
  },
  {
    id: "desert-types",
    title: "Desert Types",
    description: "Morocco contains three distinct desert landscapes, each with different terrain and character.",
    terms: [
      {
        id: "erg",
        term: "Erg",
        pronunciation: "urg",
        arabicScript: "عرق",
        category: "desert-types",
        definition: "A sand dune desert characterized by rolling dunes formed by wind-deposited sand. Morocco's two major ergs are Erg Chebbi near Merzouga and Erg Chigaga near M'Hamid.",
        context: "When most visitors imagine the Sahara, they picture an erg—the classic golden dunes.",
        related: ["Sahara", "Merzouga", "M'Hamid", "Erg Chebbi", "Erg Chigaga"],
        seeAlso: ["hammada", "reg"],
      },
      {
        id: "hammada",
        term: "Hammada",
        pronunciation: "ha-MAH-da",
        arabicScript: "حمادة",
        category: "desert-types",
        definition: "A stone or rock plateau desert, characterized by barren, hard, rocky surfaces with minimal sand. The Agafay Desert near Marrakech is a hammada.",
        context: "Unlike the dunes of an erg, a hammada offers stark, lunar landscapes of ochre rock stretching to the horizon.",
        related: ["Agafay", "stone desert", "rock desert"],
        seeAlso: ["erg", "reg"],
      },
      {
        id: "reg",
        term: "Reg",
        pronunciation: "reg",
        arabicScript: "رق",
        category: "desert-types",
        definition: "A gravel plain desert, covered with small stones and pebbles rather than sand or large rocks. Also called serir in some regions.",
        context: "Much of Morocco's desert terrain is technically reg—the flat, gravelly expanses between mountain ranges.",
        seeAlso: ["erg", "hammada"],
      },
    ],
  },
  {
    id: "architecture",
    title: "Architecture",
    description: "Traditional Moroccan building types and architectural elements.",
    terms: [
      {
        id: "riad",
        term: "Riad",
        pronunciation: "ree-YAD",
        arabicScript: "رياض",
        category: "architecture",
        definition: "A traditional Moroccan house or palace with an interior garden or courtyard. The name derives from the Arabic word for garden (ryad). Riads are built inward, with rooms arranged around a central open space, often featuring a fountain, trees, or tiles.",
        context: "Most riads in the medinas have been converted to guesthouses, offering an intimate alternative to hotels.",
        related: ["Moroccan architecture", "courtyard house", "traditional accommodation"],
        seeAlso: ["dar", "medina"],
        relatedStories: [
          { slug: "the-garden-within", title: "The Garden Within" },
          { slug: "architecture-of-privacy", title: "Architecture of Privacy" },
        ],
        relatedPlaces: [
          { slug: "marrakech", title: "Marrakech" },
          { slug: "fes", title: "Fes" },
        ],
      },
      {
        id: "dar",
        term: "Dar",
        pronunciation: "dar",
        arabicScript: "دار",
        category: "architecture",
        definition: "A traditional Moroccan townhouse, similar to a riad but typically smaller and without a garden—featuring a simple courtyard with a light well instead.",
        context: "The distinction between dar and riad is often blurred in tourism marketing, with many dars called riads.",
        seeAlso: ["riad"],
      },
      {
        id: "kasbah",
        term: "Kasbah",
        pronunciation: "KAZ-bah",
        arabicScript: "قصبة",
        category: "architecture",
        definition: "A fortified stronghold or citadel, typically built of pisé (rammed earth). Kasbahs served as the residences of local chieftains and as defensive structures along trade routes.",
        context: "The kasbahs of the Draa Valley and Dades Gorge date from the 17th-19th centuries, built to protect caravan routes.",
        related: ["fortress", "citadel", "pisé", "rammed earth"],
        seeAlso: ["ksar", "pise"],
        relatedJourneys: [
          { slug: "7-Day-Kasbahs-Route", title: "Route of the Kasbahs" },
          { slug: "10-Day-Southern-Oases", title: "Southern Oases Route" },
        ],
        relatedStories: [
          { slug: "the-fortress-of-grain", title: "The Fortress of Grain" },
          { slug: "castles-of-clay", title: "Castles of Clay" },
        ],
        relatedPlaces: [
          { slug: "ait-benhaddou", title: "Aït Benhaddou" },
          { slug: "ouarzazate", title: "Ouarzazate" },
        ],
      },
      {
        id: "ksar",
        term: "Ksar",
        pronunciation: "k-SAR",
        arabicScript: "قصر",
        category: "architecture",
        definition: "A fortified village, larger than a kasbah, consisting of multiple dwellings surrounded by defensive walls. Plural: ksour.",
        context: "Ait Benhaddou is Morocco's most famous ksar, a UNESCO World Heritage site.",
        related: ["fortified village", "Ait Benhaddou", "ksour"],
        seeAlso: ["kasbah"],
      },
      {
        id: "medina",
        term: "Medina",
        pronunciation: "meh-DEE-na",
        arabicScript: "مدينة",
        category: "architecture",
        definition: "The old walled city center, characterized by narrow winding streets, traditional architecture, and car-free zones. Morocco's imperial cities—Fes, Marrakech, Meknes, and Rabat—each have historic medinas.",
        context: "Fes el-Bali is the world's largest car-free urban area and one of the best-preserved medieval cities.",
        related: ["old city", "walled city", "Fes el-Bali", "historic quarter"],
        seeAlso: ["derb", "souk"],
        relatedJourneys: [
          { slug: "8-Day-Imperial-Cities", title: "Imperial Cities Journey" },
        ],
        relatedStories: [
          { slug: "the-labyrinth", title: "The Labyrinth" },
          { slug: "streets-without-names", title: "Streets Without Names" },
        ],
        relatedPlaces: [
          { slug: "marrakech", title: "Marrakech" },
          { slug: "fes", title: "Fes" },
          { slug: "chefchaouen", title: "Chefchaouen" },
        ],
      },
      {
        id: "derb",
        term: "Derb",
        pronunciation: "derb",
        arabicScript: "درب",
        category: "architecture",
        definition: "A narrow alley or lane within a medina, often dead-ending at a cluster of houses.",
        context: "Medina addresses typically reference the derb name rather than street numbers.",
        seeAlso: ["medina"],
      },
      {
        id: "pise",
        term: "Pisé",
        pronunciation: "pee-ZAY",
        category: "architecture",
        definition: "Rammed earth construction technique using compacted layers of soil, clay, and straw. The traditional building material for kasbahs and ksour in southern Morocco.",
        context: "Pisé buildings require constant maintenance; without repair, they dissolve back into the earth within decades.",
        related: ["rammed earth", "adobe", "earth construction"],
        seeAlso: ["kasbah", "ksar"],
      },
    ],
  },
  {
    id: "commerce-craft",
    title: "Commerce & Craft",
    description: "Traditional markets, workshops, and artisanal techniques.",
    terms: [
      {
        id: "souk",
        term: "Souk",
        pronunciation: "sook",
        arabicScript: "سوق",
        category: "commerce-craft",
        definition: "A traditional market or bazaar, typically organized by trade or product type. Souks may be permanent structures within a medina or weekly open-air markets in rural areas.",
        context: "Marrakech's souks are organized by craft: the souk of dyers, the souk of metalworkers, the souk of leather goods.",
        related: ["market", "bazaar", "marketplace"],
        seeAlso: ["medina", "fondouk"],
        relatedStories: [
          { slug: "the-way-of-the-souk", title: "The Way of the Souk" },
          { slug: "merchants-and-makers", title: "Merchants and Makers" },
        ],
        relatedPlaces: [
          { slug: "marrakech", title: "Marrakech" },
          { slug: "fes", title: "Fes" },
        ],
      },
      {
        id: "fondouk",
        term: "Fondouk",
        pronunciation: "fon-DOOK",
        arabicScript: "فندق",
        category: "commerce-craft",
        definition: "A historic caravanserai or merchants' inn, typically featuring a central courtyard surrounded by two stories of rooms and storage. Many now serve as artisan workshops.",
        context: "Fes has over 100 historic fondouks, some dating to the 13th century.",
        related: ["caravanserai", "khan", "merchants' inn"],
        seeAlso: ["souk"],
      },
      {
        id: "zellige",
        term: "Zellige",
        pronunciation: "zel-LEEJ",
        arabicScript: "زليج",
        category: "commerce-craft",
        definition: "Traditional Moroccan mosaic tilework made from hand-cut geometric pieces of glazed terracotta. Each piece is individually chiseled and assembled face-down to create intricate patterns.",
        context: "Zellige work requires years of apprenticeship. The craft is centered in Fes, where master craftsmen (maâlems) maintain techniques unchanged for centuries.",
        related: ["mosaic", "tilework", "Islamic geometric art", "Moroccan tiles"],
        seeAlso: ["maalem"],
        relatedStories: [
          { slug: "the-geometry-of-faith", title: "The Geometry of Faith" },
          { slug: "the-last-zellige-master", title: "The Last Zellige Master" },
        ],
        relatedPlaces: [
          { slug: "fes", title: "Fes" },
          { slug: "meknes", title: "Meknes" },
        ],
      },
      {
        id: "tadelakt",
        term: "Tadelakt",
        pronunciation: "TAD-el-akt",
        arabicScript: "تدلاكت",
        category: "commerce-craft",
        definition: "A traditional waterproof lime plaster, polished with flat stones and treated with olive oil soap. Originally used in hammams, now popular for bathrooms and feature walls.",
        context: "Authentic tadelakt uses lime from the Marrakech region and requires specialized application techniques.",
        related: ["lime plaster", "Moroccan plaster", "waterproof finish"],
      },
      {
        id: "khettara",
        term: "Khettara",
        pronunciation: "khe-TAR-ah",
        arabicScript: "خطارة",
        category: "commerce-craft",
        definition: "An ancient underground irrigation system using gravity-fed tunnels to channel water from mountain aquifers to agricultural areas. Similar to Persian qanats. Some date back over 1,000 years.",
        context: "The khettaras of the Tafilalt oasis once numbered over 300; today fewer than 30 remain functional.",
        related: ["qanat", "irrigation", "underground canal", "foggara"],
      },
    ],
  },
  {
    id: "people-culture",
    title: "People & Culture",
    description: "Ethnic groups, languages, and cultural traditions.",
    terms: [
      {
        id: "amazigh",
        term: "Amazigh",
        pronunciation: "ah-mah-ZEEG",
        tifinagh: "ⴰⵎⴰⵣⵉⵖ",
        arabicScript: "أمازيغ",
        category: "people-culture",
        definition: "The indigenous people of North Africa, also known as Berbers. The name means 'free people' in Tamazight. Amazigh culture predates Arab arrival by millennia.",
        context: "Approximately 40% of Moroccans are ethnically Amazigh, with the highest concentrations in the Atlas Mountains and Rif.",
        related: ["Berber", "indigenous North African", "Imazighen"],
        seeAlso: ["tamazight", "tifinagh"],
        relatedJourneys: [
          { slug: "7-Day-Atlas-Valleys", title: "Atlas Valleys Journey" },
          { slug: "10-Day-Southern-Oases", title: "Southern Oases Route" },
        ],
        relatedStories: [
          { slug: "the-free-people", title: "The Free People" },
          { slug: "the-language-of-wool", title: "The Language of Wool" },
          { slug: "symbols-in-the-weave", title: "Symbols in the Weave" },
        ],
        relatedPlaces: [
          { slug: "imlil", title: "Imlil" },
          { slug: "ouirgane", title: "Ouirgane" },
          { slug: "ait-benhaddou", title: "Aït Benhaddou" },
        ],
      },
      {
        id: "tamazight",
        term: "Tamazight",
        pronunciation: "tam-ah-ZEEGT",
        tifinagh: "ⵜⴰⵎⴰⵣⵉⵖⵜ",
        category: "people-culture",
        definition: "The family of Amazigh languages spoken across North Africa. In Morocco, the three main variants are Tashelhit (south), Tamazight (central Atlas), and Tarifit (Rif). Recognized as an official language of Morocco since 2011.",
        related: ["Berber language", "Tashelhit", "Tarifit", "Amazigh language"],
        seeAlso: ["amazigh", "tifinagh"],
      },
      {
        id: "tifinagh",
        term: "Tifinagh",
        pronunciation: "tif-in-AH",
        tifinagh: "ⵜⵉⴼⵉⵏⴰⵖ",
        category: "people-culture",
        definition: "The traditional alphabet used to write Amazigh languages, with origins dating back over 2,000 years. A modernized version was adopted for official use in Morocco in 2003.",
        context: "You'll see Tifinagh script on government buildings and road signs alongside Arabic and French.",
        related: ["Berber alphabet", "Amazigh script", "Libyco-Berber"],
        seeAlso: ["tamazight", "amazigh"],
      },
      {
        id: "gnaoua",
        term: "Gnaoua",
        pronunciation: "g-NOW-ah",
        arabicScript: "كناوة",
        category: "people-culture",
        definition: "A spiritual music tradition with roots in sub-Saharan African and Sufi practices. Gnaoua ceremonies (lilas) use hypnotic bass rhythms, metal castanets (qraqeb), and call-and-response singing.",
        context: "The Essaouira Gnaoua Festival each June is the largest celebration of this tradition.",
        related: ["Gnawa", "spiritual music", "trance music", "African diaspora"],
        seeAlso: ["lila", "maalem"],
        relatedJourneys: [
          { slug: "7-Day-Music-of-Morocco", title: "Music of Morocco" },
        ],
        relatedStories: [
          { slug: "the-sound-of-trance", title: "The Sound of Trance" },
          { slug: "spirit-possession-healing", title: "Spirit Possession & Healing" },
        ],
        relatedPlaces: [
          { slug: "essaouira", title: "Essaouira" },
          { slug: "marrakech", title: "Marrakech" },
        ],
      },
      {
        id: "lila",
        term: "Lila",
        pronunciation: "LEE-la",
        arabicScript: "ليلة",
        category: "people-culture",
        definition: "An all-night Gnaoua ceremony combining music, dance, and spiritual healing. Literally 'night' in Arabic. Each lila progresses through a sequence of ritual songs invoking different spirits (mluk).",
        context: "Authentic lilas are private spiritual ceremonies, not tourist performances.",
        related: ["Gnaoua ceremony", "spiritual healing", "trance ritual"],
        seeAlso: ["gnaoua", "maalem"],
      },
      {
        id: "maalem",
        term: "Maâlem",
        pronunciation: "mah-ah-LEM",
        arabicScript: "معلم",
        category: "people-culture",
        definition: "A master craftsman or musician. In Gnaoua tradition, a maâlem leads the spiritual ceremonies. In craft, a maâlem has completed formal apprenticeship and mastered their trade.",
        context: "The title carries significant respect—it denotes not just skill but transmission of traditional knowledge.",
        related: ["master craftsman", "master musician", "guild master"],
        seeAlso: ["gnaoua", "zellige"],
      },
      {
        id: "moussem",
        term: "Moussem",
        pronunciation: "MOO-sem",
        arabicScript: "موسم",
        category: "people-culture",
        definition: "A religious festival or pilgrimage, typically honoring a local saint (marabout). Moussems combine religious devotion with markets, music, and social gathering.",
        context: "The Imilchil Marriage Moussem in the High Atlas is one of Morocco's most famous, where young people traditionally chose marriage partners.",
        related: ["festival", "pilgrimage", "saint's day", "religious gathering"],
      },
      {
        id: "tbourida",
        term: "Tbourida",
        pronunciation: "t-boo-REE-da",
        arabicScript: "تبوريدة",
        category: "people-culture",
        definition: "A traditional Moroccan equestrian performance, also known as Fantasia. Riders in traditional dress charge in formation, firing antique rifles in synchronized volleys. A UNESCO-recognized intangible cultural heritage.",
        context: "Tbourida originated as cavalry training and evolved into ceremonial display. Teams compete at moussems and festivals across Morocco.",
        related: ["Fantasia", "equestrian", "horse riding", "gunpowder"],
        relatedJourneys: [
          { slug: "5-Day-Tbourida-Festival", title: "Tbourida by the Sea" },
        ],
        relatedStories: [
          { slug: "riders-of-the-plain", title: "Riders of the Plain" },
        ],
      },
      {
        id: "hammam",
        term: "Hammam",
        pronunciation: "ha-MAM",
        arabicScript: "حمام",
        category: "people-culture",
        definition: "A traditional public bathhouse, central to Moroccan social and cleansing rituals. Hammams feature a series of progressively hotter rooms, with scrubbing (gommage) using black soap and a rough mitt (kessa).",
        context: "Historically, hammams served as social gathering spaces, especially for women. Every neighborhood has its local hammam alongside modern spas.",
        related: ["bathhouse", "steam bath", "gommage", "kessa"],
        relatedStories: [
          { slug: "ritual-of-steam", title: "The Ritual of Steam" },
        ],
        relatedPlaces: [
          { slug: "marrakech", title: "Marrakech" },
          { slug: "fes", title: "Fes" },
        ],
      },
      {
        id: "argan",
        term: "Argan",
        pronunciation: "ar-GAN",
        arabicScript: "أركان",
        tifinagh: "ⴰⵔⴳⴰⵏ",
        category: "people-culture",
        definition: "An endemic tree species found only in Morocco's Souss region, producing nuts that are pressed into culinary and cosmetic oil. The argan forest is a UNESCO Biosphere Reserve.",
        context: "Traditional production is done by women's cooperatives. Goats famously climb argan trees to eat the fruit, though staged photo opportunities should be avoided.",
        related: ["argan oil", "Souss Valley", "women's cooperatives", "endemic species"],
        relatedStories: [
          { slug: "liquid-gold", title: "Liquid Gold" },
          { slug: "the-argan-forest", title: "The Argan Forest" },
        ],
        relatedPlaces: [
          { slug: "essaouira", title: "Essaouira" },
          { slug: "taroudant", title: "Taroudant" },
        ],
      },
    ],
  },
  {
    id: "geography",
    title: "Geography",
    description: "Mountains, valleys, and regional terminology.",
    terms: [
      {
        id: "high-atlas",
        term: "High Atlas",
        arabicScript: "الأطلس الكبير",
        category: "geography",
        definition: "Morocco's highest mountain range, running southwest to northeast for approximately 1,000 kilometers. Includes Jebel Toubkal (4,167m), the highest peak in North Africa.",
        context: "The High Atlas separates the Mediterranean climate of the north from the Saharan climate of the south.",
        related: ["Atlas Mountains", "Toubkal", "mountain range"],
        seeAlso: ["jebel", "middle-atlas", "anti-atlas"],
      },
      {
        id: "middle-atlas",
        term: "Middle Atlas",
        arabicScript: "الأطلس المتوسط",
        category: "geography",
        definition: "The northernmost of Morocco's Atlas ranges, characterized by cedar forests, lakes, and Amazigh villages. Lower and wetter than the High Atlas.",
        context: "The Middle Atlas is home to the endangered Barbary macaque and the cedar forests of Azrou.",
        related: ["Atlas Mountains", "Azrou", "Ifrane"],
        seeAlso: ["high-atlas"],
      },
      {
        id: "anti-atlas",
        term: "Anti-Atlas",
        arabicScript: "الأطلس الصغير",
        category: "geography",
        definition: "The southernmost Atlas range, older and more eroded than the High Atlas. Known for dramatic rock formations, ancient granites, and almond groves.",
        context: "The Anti-Atlas contains some of the oldest exposed rock on Earth, dating back over 2 billion years.",
        related: ["Atlas Mountains", "Tafraoute", "geological formations"],
        seeAlso: ["high-atlas"],
      },
      {
        id: "draa-valley",
        term: "Draa Valley",
        pronunciation: "drah",
        arabicScript: "وادي درعة",
        category: "geography",
        definition: "Morocco's longest river valley, stretching from the Atlas Mountains toward the Sahara. The Draa River feeds a chain of oases and palm groves, with kasbahs and ksour lining its banks.",
        context: "The valley was historically a key caravan route for trans-Saharan trade in gold, salt, and slaves.",
        related: ["Draa River", "palm oasis", "caravan route"],
        seeAlso: ["kasbah", "ksar", "oasis"],
      },
      {
        id: "jebel",
        term: "Jebel",
        pronunciation: "JEB-el",
        arabicScript: "جبل",
        category: "geography",
        definition: "Mountain or hill. Used in place names throughout Morocco: Jebel Toubkal, Jebel Saghro, Jebel Siroua.",
        context: "The Arabic term; the Amazigh equivalent is 'Adrar.'",
        related: ["mountain", "Adrar", "peak"],
      },
      {
        id: "oued",
        term: "Oued",
        pronunciation: "wed",
        arabicScript: "واد",
        category: "geography",
        definition: "A river or riverbed, often dry except during rainy season. Also spelled 'wadi.'",
        context: "Most Moroccan oueds are seasonal—raging torrents in spring, bone-dry wadis in summer.",
        related: ["wadi", "river", "riverbed", "seasonal river"],
      },
      {
        id: "oasis",
        term: "Oasis",
        arabicScript: "واحة",
        category: "geography",
        definition: "A fertile area in the desert sustained by groundwater or river water. Moroccan oases typically feature date palms, irrigation channels, and fortified villages (ksour).",
        context: "The Tafilalt oasis near Erfoud is one of the largest in Morocco, with over a million palm trees.",
        related: ["palm grove", "date palms", "Tafilalt", "Zagora"],
        seeAlso: ["khettara", "ksar"],
      },
    ],
  },
  {
    id: "food-drink",
    title: "Food & Drink",
    description: "Traditional Moroccan cuisine and culinary terms.",
    terms: [
      {
        id: "tagine",
        term: "Tagine",
        pronunciation: "tah-JEEN",
        arabicScript: "طاجين",
        category: "food-drink",
        definition: "Both a conical clay cooking vessel and the slow-cooked stew prepared in it. The cone-shaped lid returns condensation to the dish, allowing cooking with minimal liquid.",
        context: "Regional variations are significant: Marrakech favors sweet-savory combinations; Fes uses more preserved lemons and olives.",
        related: ["Moroccan stew", "clay pot cooking", "slow cooking"],
        relatedJourneys: [
          { slug: "5-Day-Culinary-Journey", title: "Culinary Journey" },
        ],
        relatedStories: [
          { slug: "the-slow-fire", title: "The Slow Fire" },
          { slug: "clay-and-flame", title: "Clay and Flame" },
        ],
        relatedPlaces: [
          { slug: "marrakech", title: "Marrakech" },
          { slug: "fes", title: "Fes" },
        ],
      },
      {
        id: "harira",
        term: "Harira",
        pronunciation: "ha-REE-ra",
        arabicScript: "حريرة",
        category: "food-drink",
        definition: "A tomato-based soup with chickpeas, lentils, and herbs, traditionally served to break the fast during Ramadan. Recipes vary by region and family.",
        context: "During Ramadan, harira is served at sunset with dates, chebakia (honey pastries), and hard-boiled eggs.",
        related: ["Ramadan soup", "Moroccan soup", "iftar"],
      },
      {
        id: "couscous",
        term: "Couscous",
        pronunciation: "KOOS-koos",
        arabicScript: "كسكس",
        category: "food-drink",
        definition: "Steamed semolina granules, traditionally hand-rolled and served with vegetables and meat. Friday couscous after midday prayers is a Moroccan institution.",
        context: "Authentic couscous is steamed three times over a simmering stew; instant couscous is a pale imitation.",
        related: ["seksu", "semolina", "Friday lunch"],
        relatedStories: [
          { slug: "friday-ritual", title: "The Friday Ritual" },
        ],
      },
      {
        id: "msemen",
        term: "Msemen",
        pronunciation: "m-SEH-men",
        arabicScript: "مسمن",
        category: "food-drink",
        definition: "A pan-fried flatbread made by folding and stretching dough into thin layers, creating a flaky, slightly chewy texture. Served for breakfast with honey or cheese.",
        related: ["Moroccan flatbread", "rghaif", "meloui", "breakfast bread"],
      },
      {
        id: "pastilla",
        term: "Pastilla",
        pronunciation: "pas-TEE-ya",
        arabicScript: "بسطيلة",
        category: "food-drink",
        definition: "A layered pie of thin warqa pastry filled with pigeon or chicken, almonds, eggs, and spices, dusted with cinnamon and powdered sugar. A signature dish of Fes.",
        context: "The sweet-savory combination—meat with sugar and cinnamon—reflects medieval Andalusian influence.",
        related: ["bastilla", "b'stilla", "pigeon pie", "Fassi cuisine"],
      },
      {
        id: "atay",
        term: "Atay",
        pronunciation: "ah-TAI",
        arabicScript: "أتاي",
        category: "food-drink",
        definition: "Moroccan mint tea, made with Chinese gunpowder green tea, fresh spearmint, and generous sugar. Poured from height to create a frothy top.",
        context: "Refusing tea is considered impolite. The ritual of preparation and serving is as important as the drink itself.",
        related: ["Moroccan mint tea", "whiskey Berber", "nana mint"],
      },
    ],
  },
  {
    id: "landmarks",
    title: "Landmarks & Attractions",
    description: "Morocco's most significant historical sites, monuments, and must-visit destinations.",
    terms: [
      {
        id: "medersa-ben-youssef",
        term: "Medersa Ben Youssef",
        pronunciation: "meh-DER-sa ben YOO-sef",
        arabicScript: "مدرسة بن يوسف",
        category: "landmarks",
        definition: "A 16th-century Islamic college in Marrakech, once the largest madrasa in Morocco. Built by the Saadian Sultan Abdallah al-Ghalib in 1564-1565, it housed up to 900 students studying theology, law, and rhetoric.",
        context: "The medersa's courtyard features exceptional zellige tilework, carved stucco, and cedarwood—a pinnacle of Moroccan decorative arts. Closed for renovation 2020-2024, now reopened.",
        related: ["Marrakech", "Islamic architecture", "Saadian dynasty", "madrasa"],
        seeAlso: ["zellige", "medina"],
      },
      {
        id: "palais-bahia",
        term: "Palais Bahia",
        pronunciation: "pa-LAY ba-HEE-a",
        arabicScript: "قصر الباهية",
        category: "landmarks",
        definition: "A 19th-century palace in Marrakech built for Si Moussa, grand vizier of Sultan Hassan I, and expanded by his son Ba Ahmed. The name means 'Palace of the Brilliant' or 'Palace of the Beautiful.'",
        context: "Spread over 8 hectares with 150 rooms, the palace was designed to be the greatest of its time. Each room was decorated by master craftsmen from Fes. The French Protectorate later used it as the residence of the Resident-General.",
        related: ["Marrakech", "19th-century Morocco", "Moroccan palace"],
        seeAlso: ["riad", "zellige"],
      },
      {
        id: "palais-el-badi",
        term: "Palais El Badi",
        pronunciation: "pa-LAY el ba-DEE",
        arabicScript: "قصر البديع",
        category: "landmarks",
        definition: "The ruined 16th-century palace built by Saadian Sultan Ahmed al-Mansour to celebrate the victory over the Portuguese at the Battle of the Three Kings (1578). Once one of the world's most magnificent palaces.",
        context: "Al-Mansour funded construction with Portuguese ransom money. The palace took 25 years to build, featuring gold from Sudan, Italian marble, and Irish oak. Later stripped by Moulay Ismail to build Meknes.",
        related: ["Marrakech", "Saadian dynasty", "Battle of Ksar el-Kebir"],
        seeAlso: ["saadian-tombs"],
      },
      {
        id: "saadian-tombs",
        term: "Saadian Tombs",
        pronunciation: "sah-DEE-an",
        arabicScript: "مقابر السعديين",
        category: "landmarks",
        definition: "Royal necropolis in Marrakech containing the remains of Saadian dynasty rulers, including Ahmed al-Mansour. Sealed by Moulay Ismail and forgotten until 1917 when French aerial surveys rediscovered them.",
        context: "The main mausoleum, the Hall of Twelve Columns, features Italian Carrara marble and intricate muqarnas ceilings. Some 60 members of the Saadian dynasty are buried here.",
        related: ["Marrakech", "Saadian dynasty", "mausoleum"],
        seeAlso: ["palais-el-badi"],
      },
      {
        id: "koutoubia-mosque",
        term: "Koutoubia Mosque",
        pronunciation: "koo-too-BEE-a",
        arabicScript: "جامع الكتبية",
        category: "landmarks",
        definition: "The largest mosque in Marrakech, built by the Almohad Caliph Yaqub al-Mansour in the late 12th century. Its 77-meter minaret is the city's most iconic landmark and the template for Seville's Giralda and Rabat's Hassan Tower.",
        context: "The name derives from 'kutubiyyin' (booksellers), as the mosque was once surrounded by manuscript dealers. Non-Muslims cannot enter, but the minaret dominates the skyline and is visible from across the city.",
        related: ["Marrakech", "Almohad dynasty", "mosque", "minaret"],
        seeAlso: ["medina"],
      },
      {
        id: "jardin-majorelle",
        term: "Jardin Majorelle",
        pronunciation: "jar-DAN ma-zho-REL",
        category: "landmarks",
        definition: "A botanical garden in Marrakech created by French painter Jacques Majorelle over 40 years, starting in 1923. Famous for its cobalt blue buildings (now called Majorelle Blue), bamboo groves, and cactus collection.",
        context: "The garden fell into disrepair after Majorelle's death but was rescued by Yves Saint Laurent and Pierre Bergé in 1980. It now contains the Berber Museum and YSL's memorial.",
        related: ["Marrakech", "Yves Saint Laurent", "botanical garden"],
      },
      {
        id: "jemaa-el-fna",
        term: "Jemaa el-Fna",
        pronunciation: "jeh-MAH el F-NA",
        arabicScript: "جامع الفناء",
        category: "landmarks",
        definition: "The main square in Marrakech's medina, a UNESCO-recognized 'Masterpiece of the Oral and Intangible Heritage of Humanity.' By day a market, by night a carnival of food stalls, musicians, storytellers, and performers.",
        context: "The name may mean 'assembly of the dead' (referring to public executions) or 'mosque at the end' (a destroyed Almoravid mosque). The square has been the heart of Marrakech since the city's founding.",
        related: ["Marrakech", "medina", "UNESCO", "night market"],
        seeAlso: ["souk", "medina"],
      },
      {
        id: "ait-benhaddou",
        term: "Aït Benhaddou",
        pronunciation: "ait ben-ha-DOO",
        tifinagh: "ⴰⵢⵜ ⴱⴻⵏⵀⴰⴷⴷⵓ",
        category: "landmarks",
        definition: "A UNESCO World Heritage fortified village (ksar) in the foothills of the High Atlas, along the former caravan route between Marrakech and the Sahara. One of Morocco's most photogenic sites.",
        context: "Though largely abandoned (only a few families remain), the ksar has appeared in numerous films including Lawrence of Arabia, Gladiator, and Game of Thrones. The earthen architecture requires constant restoration.",
        related: ["UNESCO", "ksar", "film location", "Ouarzazate"],
        seeAlso: ["ksar", "kasbah"],
      },
      {
        id: "fes-el-bali",
        term: "Fes el-Bali",
        pronunciation: "fes el BA-lee",
        arabicScript: "فاس البالي",
        category: "landmarks",
        definition: "The ancient walled medina of Fes, founded in the 9th century and recognized as the world's largest contiguous car-free urban area. Contains over 9,000 narrow streets, 11,000 historic buildings, and some 300 functioning mosques.",
        context: "Fes el-Bali preserves medieval urban planning virtually intact. The medina contains the University of Al-Qarawiyyin (founded 859 CE, the world's oldest continuously operating university) and the famous tanneries.",
        related: ["Fes", "medina", "UNESCO", "Al-Qarawiyyin"],
        seeAlso: ["medina", "fondouk", "souk"],
      },
      {
        id: "chouara-tannery",
        term: "Chouara Tannery",
        pronunciation: "SHWA-ra",
        arabicScript: "شوارة",
        category: "landmarks",
        definition: "The largest and oldest of Fes's medieval tanneries, operating since the 11th century. Workers process hides using traditional methods with lime, pigeon dung, and natural dyes in hundreds of stone vats.",
        context: "The tannery is best viewed from surrounding leather shops' terraces. The process and smell have remained unchanged for nearly a millennium—visitors are offered mint to mask the odor.",
        related: ["Fes", "leather", "traditional craft", "medina"],
        seeAlso: ["fes-el-bali", "souk"],
      },
      {
        id: "volubilis",
        term: "Volubilis",
        pronunciation: "vo-LOO-bi-lis",
        arabicScript: "وليلي",
        category: "landmarks",
        definition: "The best-preserved Roman ruins in Morocco, a UNESCO World Heritage site near Meknes. Founded in the 3rd century BCE, it became the Roman administrative center of Mauretania Tingitana.",
        context: "The city flourished producing olive oil and grain for Rome. Notable features include the Capitol, Basilica, and several houses with intact mosaic floors. Largely abandoned after an earthquake in 1755.",
        related: ["Roman Morocco", "Meknes", "UNESCO", "ancient ruins", "Moulay Idriss"],
      },
      {
        id: "hassan-tower",
        term: "Hassan Tower",
        pronunciation: "HA-san",
        arabicScript: "صومعة حسان",
        category: "landmarks",
        definition: "An incomplete 12th-century minaret in Rabat, intended for what would have been the world's largest mosque. Construction halted when Sultan Yaqub al-Mansour died in 1199; the tower reached only 44 of its planned 86 meters.",
        context: "The site now includes the Mausoleum of Mohammed V and remains of 348 columns that would have supported the mosque. The minaret shares the same Almohad design as the Koutoubia and Seville's Giralda.",
        related: ["Rabat", "Almohad dynasty", "minaret", "Mausoleum of Mohammed V"],
        seeAlso: ["koutoubia-mosque"],
      },
      {
        id: "chefchaouen",
        term: "Chefchaouen",
        pronunciation: "shef-SHA-wen",
        arabicScript: "شفشاون",
        tifinagh: "ⵛⴻⴼⵛⴰⵡⴻⵏ",
        category: "landmarks",
        definition: "A mountain town in the Rif known for its distinctive blue-washed buildings. Founded in 1471 as a fortress against Portuguese invasion, it later became a refuge for Jews and Moors expelled from Spain.",
        context: "The blue color tradition has various explanations: Jewish residents painting homes to represent the sky and heaven, mosquito repellent properties, or simply keeping buildings cool. The medina was closed to foreigners until 1920.",
        related: ["Rif Mountains", "blue city", "medina", "Andalusian refugees"],
        seeAlso: ["medina"],
        relatedJourneys: [
          { slug: "10-Day-Northern-Morocco", title: "Northern Morocco" },
          { slug: "7-Day-Rif-Mountains", title: "Rif Mountains Journey" },
        ],
        relatedStories: [
          { slug: "the-blue-maze", title: "The Blue Maze" },
          { slug: "fifty-shades-of-blue", title: "Fifty Shades of Blue" },
        ],
        relatedPlaces: [
          { slug: "chefchaouen", title: "Chefchaouen" },
        ],
      },
      {
        id: "erg-chebbi",
        term: "Erg Chebbi",
        pronunciation: "urg SHEB-bee",
        arabicScript: "عرق الشبي",
        category: "landmarks",
        definition: "Morocco's largest sand dune field, near the village of Merzouga. The orange-gold dunes reach heights of 150 meters and stretch approximately 22 kilometers long by 5 kilometers wide.",
        context: "Erg Chebbi is Morocco's most accessible Saharan dune experience, about 9 hours from Marrakech. The area is home to the Ait Khebbach nomads and seasonal flamingo populations at Dayet Srji lake.",
        related: ["Sahara", "Merzouga", "sand dunes", "desert"],
        seeAlso: ["erg"],
        relatedJourneys: [
          { slug: "3-Day-Desert-Experience", title: "Sahara Desert Experience" },
          { slug: "8-Day-Desert-Circle", title: "The Desert Circle" },
        ],
        relatedStories: [
          { slug: "stars-over-sand", title: "Stars Over Sand" },
          { slug: "the-blue-men", title: "The Blue Men" },
        ],
        relatedPlaces: [
          { slug: "merzouga", title: "Merzouga" },
        ],
      },
      {
        id: "todra-gorge",
        term: "Todra Gorge",
        pronunciation: "TOD-ra",
        arabicScript: "مضيق تودرا",
        category: "landmarks",
        definition: "A canyon carved by the Todra River through the eastern High Atlas, with sheer limestone walls rising 300 meters on either side. At its narrowest point, the gorge is only 10 meters wide.",
        context: "The gorge is a popular rock climbing destination with routes for all skill levels. The paved road through the canyon passes traditional Berber villages and palm oases.",
        related: ["High Atlas", "canyon", "rock climbing", "Tinghir"],
        relatedJourneys: [
          { slug: "10-Day-Southern-Oases", title: "Southern Oases Route" },
        ],
        relatedPlaces: [
          { slug: "tinghir", title: "Tinghir" },
        ],
      },
      {
        id: "dades-valley",
        term: "Dades Valley",
        pronunciation: "da-DES",
        arabicScript: "وادي دادس",
        category: "landmarks",
        definition: "A river valley running through the High Atlas, known as the 'Valley of a Thousand Kasbahs' for its concentration of historic fortified structures. The Dades Gorge offers dramatic rock formations including 'monkey fingers.'",
        context: "The valley was a crucial segment of trans-Saharan trade routes. Today it's famous for its roses—the annual Rose Festival in Kelaat M'Gouna celebrates the harvest used for rosewater and cosmetics.",
        related: ["High Atlas", "kasbahs", "Rose Valley", "Kelaat M'Gouna"],
        seeAlso: ["kasbah"],
        relatedJourneys: [
          { slug: "7-Day-Kasbahs-Route", title: "Route of the Kasbahs" },
        ],
        relatedStories: [
          { slug: "valley-of-roses", title: "Valley of Roses" },
        ],
        relatedPlaces: [
          { slug: "kelaat-mgouna", title: "Kelaat M'Gouna" },
          { slug: "boumalne-dades", title: "Boumalne Dades" },
        ],
      },
      {
        id: "essaouira-medina",
        term: "Essaouira Medina",
        pronunciation: "es-a-WEER-a",
        arabicScript: "الصويرة",
        category: "landmarks",
        definition: "An 18th-century fortified port city on Morocco's Atlantic coast, designed by French architect Théodore Cornut for Sultan Mohammed III. A UNESCO World Heritage site known for its blend of Moroccan and European architecture.",
        context: "Once called Mogador, the city served as Morocco's primary trading port. Today it's known for wind sports, its annual Gnaoua World Music Festival, and a thriving arts scene. Jimi Hendrix famously visited in 1969.",
        related: ["Atlantic coast", "UNESCO", "Gnaoua", "port city"],
        seeAlso: ["gnawa", "medina"],
        relatedJourneys: [
          { slug: "3-Day-Marrakech-Essaouira", title: "Marrakech & Essaouira" },
        ],
        relatedStories: [
          { slug: "the-wind-city", title: "The Wind City" },
          { slug: "port-of-timbuktu", title: "Port of Timbuktu" },
        ],
        relatedPlaces: [
          { slug: "essaouira", title: "Essaouira" },
        ],
      },
    ],
  },
  {
    id: "textiles-weaving",
    title: "Textiles & Weaving",
    description: "Traditional Moroccan textiles, weaving techniques, and the cultural significance of rugs and fabrics.",
    terms: [
      {
        id: "kilim",
        term: "Kilim",
        pronunciation: "kee-LEEM",
        arabicScript: "كليم",
        category: "textiles-weaving",
        definition: "A flat-woven textile without pile, created by tightly interweaving warp and weft threads. Moroccan kilims feature bold geometric patterns and are lighter than knotted rugs.",
        context: "Kilims are practical textiles used as floor coverings, wall hangings, and saddle blankets. The flat weave makes them reversible and easier to transport.",
        related: ["flatweave", "carpet", "tapestry", "hanbel"],
        relatedStories: [
          { slug: "the-language-of-wool", title: "The Language of Wool" },
          { slug: "flat-weave-traditions", title: "Flat Weave Traditions" },
        ],
      },
      {
        id: "boucherouite",
        term: "Boucherouite",
        pronunciation: "boo-sheh-REET",
        arabicScript: "بوشروط",
        category: "textiles-weaving",
        definition: "A rag rug made from recycled fabric scraps, traditionally created in regions where wool was scarce. The name derives from 'bu sherwit' (father of rags). Characterized by vibrant, abstract compositions.",
        context: "Once considered poor women's craft, boucherouite rugs gained international recognition as folk art in the late 20th century. Each rug tells the story of its materials—old clothes, fabric samples, industrial scraps.",
        related: ["rag rug", "recycled textile", "upcycled art", "folk art"],
        relatedStories: [
          { slug: "rags-to-art", title: "Rags to Art" },
          { slug: "the-scrap-weavers", title: "The Scrap Weavers" },
        ],
      },
      {
        id: "beni-ourain",
        term: "Beni Ourain",
        pronunciation: "BEN-ee wah-RAIN",
        arabicScript: "بني وران",
        tifinagh: "ⴱⵏⵉ ⵡⵔⴰⵢⵏ",
        category: "textiles-weaving",
        definition: "A style of thick, plush wool rug from the Beni Ourain tribe of the Middle Atlas mountains. Characterized by cream-white wool with dark geometric patterns—typically diamonds and lines.",
        context: "These rugs gained Western popularity after Le Corbusier featured them in his designs. Authentic Beni Ourain rugs use undyed wool from mountain sheep and can take months to complete.",
        related: ["Middle Atlas", "Amazigh rug", "tribal carpet", "natural wool"],
        relatedJourneys: [
          { slug: "7-Day-Atlas-Valleys", title: "Atlas Valleys Journey" },
        ],
        relatedStories: [
          { slug: "white-wool-black-diamonds", title: "White Wool, Black Diamonds" },
          { slug: "weavers-of-the-atlas", title: "Weavers of the Atlas" },
        ],
        relatedPlaces: [
          { slug: "azrou", title: "Azrou" },
          { slug: "ifrane", title: "Ifrane" },
        ],
      },
      {
        id: "hanbel",
        term: "Hanbel",
        pronunciation: "HAN-bel",
        arabicScript: "حنبل",
        category: "textiles-weaving",
        definition: "A traditional Moroccan flatweave blanket or rug, typically featuring horizontal stripes in bold colors. Used as bedding, floor covering, and ceremonial textile.",
        context: "Hanbels are among the most practical Moroccan textiles, lightweight and multipurpose. Regional variations include the striped hanbels of the Middle Atlas and the geometric patterns of the South.",
        related: ["blanket", "flatweave", "striped textile", "bedding"],
        relatedStories: [
          { slug: "stripes-of-the-atlas", title: "Stripes of the Atlas" },
        ],
      },
      {
        id: "azilal",
        term: "Azilal",
        pronunciation: "ah-zee-LAL",
        arabicScript: "أزيلال",
        category: "textiles-weaving",
        definition: "A style of Berber rug from the Azilal province in the central High Atlas. Known for expressive, asymmetrical designs combining knotted pile with flatweave sections and often incorporating symbolic motifs.",
        context: "Azilal rugs are distinguished by their creative freedom—weavers often improvise patterns, creating unique compositions that reflect personal expression alongside traditional symbols.",
        related: ["High Atlas", "Berber rug", "mixed technique", "tribal art"],
        relatedJourneys: [
          { slug: "5-Day-Toubkal-Trek", title: "Toubkal Trek" },
        ],
        relatedStories: [
          { slug: "free-hand-weavers", title: "Free Hand Weavers" },
        ],
        relatedPlaces: [
          { slug: "azilal", title: "Azilal" },
        ],
      },
      {
        id: "sabra",
        term: "Sabra",
        pronunciation: "SAB-ra",
        arabicScript: "صبرا",
        category: "textiles-weaving",
        definition: "A silk-like fabric made from cactus fiber (agave) or rayon, used for decorative textiles including cushion covers and throws. Known for its shimmering appearance and vibrant colors.",
        context: "Modern 'sabra silk' is often synthetic, though traditional production used fibers from the aloe cactus. The material is popular in contemporary Moroccan interior design.",
        related: ["cactus silk", "agave fiber", "decorative textile", "cushion cover"],
        relatedStories: [
          { slug: "silk-of-the-desert", title: "Silk of the Desert" },
        ],
      },
      {
        id: "loom",
        term: "Loom (Azetta)",
        pronunciation: "ah-ZET-ta",
        tifinagh: "ⴰⵣⴻⵜⵜⴰ",
        category: "textiles-weaving",
        definition: "The frame on which textiles are woven. Traditional Amazigh looms are vertical structures, often set up against house walls. The word 'azetta' in Tamazight also means 'writing' or 'language.'",
        context: "The loom holds spiritual significance—weaving is considered a form of communication with ancestors. Setting up a new loom involves ritual blessing.",
        related: ["weaving frame", "vertical loom", "traditional craft"],
        relatedStories: [
          { slug: "the-first-language", title: "The First Language" },
          { slug: "sacred-geometry", title: "Sacred Geometry" },
        ],
      },
    ],
  },
];

// Helper function to get all terms as flat array
export function getAllTerms(): GlossaryTerm[] {
  return glossaryData.flatMap(category => category.terms);
}

// Helper function to get term by ID
export function getTermById(id: string): GlossaryTerm | undefined {
  return getAllTerms().find(term => term.id === id);
}

// Helper function to search terms
export function searchTerms(query: string): GlossaryTerm[] {
  const q = query.toLowerCase();
  return getAllTerms().filter(term => 
    term.term.toLowerCase().includes(q) ||
    term.definition.toLowerCase().includes(q) ||
    term.related?.some(r => r.toLowerCase().includes(q))
  );
}
